---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: demo
    role: backend
spec:
  ports:
  - port: 80
  selector:
    app: demo
    role: backend 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo
        role: backend
    spec:
      containers:
      - name: demo-backend
        image: cilium/demo-httpd
        ports:
        - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: demo
        role: frontend
    spec:
      containers:
      - name: demo-frontend
        image: cilium/demo-client
        command: [ "sleep" ]
        args:
          - "1000h"
